@extends('manufacturer.from')
@section('actionRoute', route('manufacturer.update', ['manufacturer' => $manufacturer]))
@section('method')
    @method('PUT')
@endsection
@section('name', old('name', $manufacturer->name))
@section('description', old('description', $manufacturer->description))
@section('country', old('country', $manufacturer->country))
@section('region', old('region', $manufacturer->region))
@section('city', old('city', $manufacturer->city))
@section('street', old('street', $manufacturer->street))
@section('house', old('house', $manufacturer->house))
@section('post_index', old('post_index', $manufacturer->post_index))
@section('buttonText', 'Сохранить')
