@extends('supplier.from')
@section('actionRoute', route('supplier.update', ['supplier' => $supplier]))
@section('method')
    @method('PUT')
@endsection
@section('name', old('name', $supplier->name))
@section('email', old('email', $supplier->email))
@section('country', old('country', $supplier->country))
@section('region', old('region', $supplier->region))
@section('city', old('city', $supplier->city))
@section('street', old('street', $supplier->street))
@section('house', old('house', $supplier->house))
@section('post_index', old('post_index', $supplier->post_index))
@section('last_name', old('last_name', $supplier->last_name))
@section('first_name', old('first_name', $supplier->first_name))
@section('third_name', old('third_name', $supplier->third_name))
@section('phone', old('phone', $supplier->phone))
@section('buttonText', 'Сохранить')
