@extends('client.from')
@section('actionRoute', route('client.store'))
@section('last_name', old('last_name'))
@section('first_name', old('first_name'))
@section('third_name', old('third_name'))
@section('email', old('email'))
@section('phone', old('phone'))
@section('country', old('country'))
@section('region', old('region'))
@section('city', old('city'))
@section('street', old('street'))
@section('house', old('house'))
@section('post_index', old('post_index'))
@section('buttonText', 'Добавить')
